/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module good_mux(i0, i1, sel, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input sel;
  wire sel;
  output y;
  wire y;
  assign y = sel ? i1 : i0;
endmodule
